name: build-linux
runs:
  using: composite
  steps:
    - name: build-image
      shell: bash
      run: |
        pushd "$(mktemp -d)"
        curl -f -L --retry 5 https://github.com/tweag/rust-alpine-mimalloc/archive/refs/heads/master.tar.gz | tar xz --strip-components=1
        podman build \
          --network host \
          --pull \
          --squash-all \
          --tag rust:alpine-mimalloc \
          .
        popd

    - name: build & test
      shell: bash
      run: |
        podman run \
          --env GITHUB_REF_NAME=$GITHUB_REF_NAME \
          --init \
          --network host \
          --rm \
          --volume $PWD:/workspace \
          --workdir /workspace \
          rust:alpine-mimalloc \
          /workspace/build-static.sh

    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: binaryen-${{ matrix.arch }}-linux-static
        path: binaryen-*-${{ matrix.arch }}-linux-static.tar.gz
